registry_fct_orders:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-20
    retries: 1
    retry_delay_sec: 60
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized orders' fact table"
  tasks:
    dbt_snapshot_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_orders'
    trigger_customer_dag:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'registry_dim_customer'
      wait_for_completion: True
    dbt_run_registry_stg_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_orders'
      dependencies: [ dbt_snapshot_orders ]
    dbt_test_registry_stg_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'registry_stg_orders'
      dependencies: [ dbt_run_registry_stg_orders ]
    dbt_run_registry_fct_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_fct_orders'
      dependencies: [ dbt_test_registry_stg_orders, trigger_customer_dag ]
    dbt_test_registry_fct_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'registry_fct_orders'
      dependencies: [ dbt_run_registry_fct_orders ]
