kpi:
  default_args:
    owner: 'v.folin@reply.it'
    retries: 1
    retry_delay_sec: 60
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To compute KPIs and send alerts"
  tasks:
    compute_supplier_lead_time:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'kpi_supplier_lead_time'
    check_supplier_lead_time:
      operator: airflow.providers.snowflake.operators.snowflake.SnowflakeCheckOperator
      sql: check_kpi.sql
      parameters: {'check': 'WHERE AVG_DELIVERY_DAYS > 15'}
      dependencies: [ compute_supplier_lead_time ]