select
    UNIQUE_ID,
	SHORT_NAME as TEST_SHORT_NAME,
	JSON_EXTRACT_PATH_TEXT(META, 'owner') as TEST_OWNERS,
	TRANSLATE(MODEL_OWNERS, '["]', '') as MODEL_OWNERS,
--	TRANSLATE(MODEL_TAGS, '["]', '') as MODEL_TAGS,
	DESCRIPTION,
	ORIGINAL_PATH,
	GENERATED_AT

from {{ source('elementary', 'dbt_tests') }}