materialize_registries:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-01-03
    retries: 0
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized tables"
  tasks:
    trigger_int_nation:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'int_nation'
      wait_for_completion: True
      deferrable: True
      failed_states: [ 'failed' ]
    trigger_registry_dim_part:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'registry_dim_part'
      wait_for_completion: True
      deferrable: True
      failed_states: [ 'failed' ]
    trigger_registry_dim_customer:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'registry_dim_customer'
      wait_for_completion: True
      deferrable: True
      failed_states: [ 'failed' ]
      dependencies: [ trigger_int_nation ]
    trigger_registry_dim_supplier:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'registry_dim_supplier'
      wait_for_completion: True
      deferrable: True
      failed_states: [ 'failed' ]
      dependencies: [ trigger_int_nation ]
    trigger_registry_fct_inventory:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'registry_fct_inventory'
      wait_for_completion: True
      deferrable: True
      failed_states: [ 'failed' ]
      dependencies: [ trigger_registry_dim_supplier, trigger_registry_dim_part ]
    trigger_registry_fct_orders:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'registry_fct_orders'
      wait_for_completion: True
      deferrable: True
      failed_states: [ 'failed' ]
      dependencies: [ trigger_registry_dim_customer ]
    trigger_registry_fct_sales:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'registry_fct_sales'
      wait_for_completion: True
      deferrable: True
      failed_states: [ 'failed' ]
      dependencies: [ trigger_registry_fct_orders, trigger_registry_fct_inventory ]