fct_orders:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-20
    retries: 1
    retry_delay_sec: 60
    snowflake_conn_id: snowflake
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized orders' fact table"
  tasks:
    dbt_snapshot_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_orders'
    check_registry_stg_orders_initialization:
      operator: airflow.providers.snowflake.operators.snowflake.SnowflakeCheckOperator
      sql: |
        SELECT ROW_COUNT
        FROM ANALYTICS.INFORMATION_SCHEMA.TABLES
        WHERE  table_schema = 'ANALYTICS_ENGINEERING_DATA_PIPELINE'
        AND    table_name   = 'REGISTRY_STG_ORDERS'
    branch_on_registry_stg_orders_initialization:
      operator: airflow.operators.python.BranchPythonOperator
      python_callable_file: /home/airflow/gcs/dags/dag_factory_version/historical/sales_factory/utils.py
      python_callable_name: branch_func_on_registry_stg_orders_initialization
      provide_context: True
      trigger_rule: 'all_done'
      dependencies: [ dbt_snapshot_orders, check_registry_stg_orders_initialization ]
    dbt_run_registry_stg_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_orders'
      dependencies: [ branch_on_registry_stg_orders_initialization ]
    dbt_run_registry_stg_orders_full_refresh:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_orders'
      full_refresh: True
      dependencies: [ branch_on_registry_stg_orders_initialization ]
    dbt_run_fct_orders:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'fct_orders'
      trigger_rule: 'none_failed'
      dependencies: [ dbt_run_registry_stg_orders, dbt_run_registry_stg_orders_full_refresh ]
fct_sales:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-20
    retries: 1
    retry_delay_sec: 60
    snowflake_conn_id: snowflake
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized sales' fact table"
  tasks:
    dbt_snapshot_lineitem:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_lineitem'
    check_registry_stg_lineitem_initialization:
      operator: airflow.providers.snowflake.operators.snowflake.SnowflakeCheckOperator
      sql: |
        SELECT ROW_COUNT
        FROM ANALYTICS.INFORMATION_SCHEMA.TABLES
        WHERE  table_schema = 'ANALYTICS_ENGINEERING_DATA_PIPELINE'
        AND    table_name   = 'REGISTRY_STG_LINEITEM'
    branch_on_registry_stg_lineitem_initialization:
      operator: airflow.operators.python.BranchPythonOperator
      python_callable_file: /home/airflow/gcs/dags/dag_factory_version/historical/sales_factory/utils.py
      python_callable_name: branch_func_on_registry_stg_lineitem_initialization
      provide_context: True
      trigger_rule: 'all_done'
      dependencies: [ dbt_snapshot_lineitem, check_registry_stg_lineitem_initialization ]
    dbt_run_registry_stg_lineitem:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_lineitem'
      dependencies: [ branch_on_registry_stg_lineitem_initialization ]
    dbt_run_registry_stg_lineitem_full_refresh:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_lineitem'
      full_refresh: True
      dependencies: [ branch_on_registry_stg_lineitem_initialization ]
    dbt_run_fct_sales:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'fct_sales'
      trigger_rule: 'none_failed'
      dependencies: [ dbt_run_registry_stg_lineitem, dbt_run_registry_stg_lineitem_full_refresh ]