version: 2

models:
  - name: dim_part
    description: Historicized table of products' information.
    columns:
      - name: partition_date
        description: Time when this snapshot row was inserted.
        tests:
          - not_null
          - dbt_utils.accepted_range:
              max_value: "getdate()"
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
  - name: fct_inventory
    description: Historicized table of products' information, per suppliers.
    columns:
      - name: partition_date
        description: Time when this snapshot row was inserted.
        tests:
          - not_null
          - dbt_utils.accepted_range:
              max_value: "getdate()"
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date