create or replace TRANSIENT TABLE ANALYTICS.DBT_CORE_REUSABLE_DEMO.REGISTRY_STG_ORDERS (
	ORDERKEY NUMBER(38,0),
	CUSTKEY NUMBER(38,0),
	ORDERSTATUS VARCHAR(1),
	TOTALPRICE NUMBER(12,2),
	ORDERDATE DATE,
	ORDERPRIORITY VARCHAR(15),
	CLERK VARCHAR(15),
	SHIPPRIORITY NUMBER(38,0),
	PARTITION_DATE DATE
);

create or replace TRANSIENT TABLE ANALYTICS.DBT_CORE_REUSABLE_DEMO.REGISTRY_STG_CUSTOMER (
	CUSTKEY NUMBER(38,0),
	CUST_NAME VARCHAR(25),
	NATIONKEY NUMBER(38,0),
	CUST_ACCTBAL NUMBER(12,2),
	CUST_MKTSEGMENT VARCHAR(10),
	PARTITION_DATE DATE
)