dim_customer:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-20
    retries: 1
    retry_delay_sec: 60
    snowflake_conn_id: snowflake
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized customers' dimension table"
  tasks:
    dbt_snapshot_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_customer'
    check_registry_stg_customer_initialization:
      operator: airflow.providers.snowflake.operators.snowflake.SnowflakeCheckOperator
      sql: |
        SELECT ROW_COUNT
        FROM ANALYTICS.INFORMATION_SCHEMA.TABLES
        WHERE  table_schema = 'DBT_CORE_REUSABLE_DEMO'
        AND    table_name   = 'REGISTRY_STG_CUSTOMER'
    branch_on_registry_stg_customer_initialization:
      operator: airflow.operators.python.BranchPythonOperator
      python_callable_file: /home/airflow/gcs/dags/dag_factory_version/historical/individuals_factory/utils.py
      python_callable_name: branch_func_on_registry_stg_customer_initialization
      provide_context: True
      trigger_rule: 'all_done'
      dependencies: [ dbt_snapshot_customer, check_registry_stg_customer_initialization ]
    dbt_run_registry_stg_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_customer'
      dependencies: [ branch_on_registry_stg_customer_initialization ]
    dbt_run_registry_stg_customer_full_refresh:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_customer'
      full_refresh: True
      dependencies: [ branch_on_registry_stg_customer_initialization ]
    dbt_run_dim_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'dim_customer'
      trigger_rule: 'none_failed'
      dependencies: [ dbt_run_registry_stg_customer, dbt_run_registry_stg_customer_full_refresh ]
dim_supplier:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-20
    retries: 1
    retry_delay_sec: 60
    snowflake_conn_id: snowflake
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized suppliers' dimension table"
  tasks:
    dbt_snapshot_supplier:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_supplier'
    check_registry_stg_supplier_initialization:
      operator: airflow.providers.snowflake.operators.snowflake.SnowflakeCheckOperator
      sql: |
        SELECT ROW_COUNT
        FROM ANALYTICS.INFORMATION_SCHEMA.TABLES
        WHERE  table_schema = 'DBT_CORE_REUSABLE_DEMO'
        AND    table_name   = 'REGISTRY_STG_SUPPLIER'
    branch_on_registry_stg_supplier_initialization:
      operator: airflow.operators.python.BranchPythonOperator
      python_callable_file: /home/airflow/gcs/dags/dag_factory_version/historical/individuals_factory/utils.py
      python_callable_name: branch_func_on_registry_stg_supplier_initialization
      provide_context: True
      trigger_rule: 'all_done'
      dependencies: [ dbt_snapshot_supplier, check_registry_stg_supplier_initialization ]
    dbt_run_registry_stg_supplier:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_supplier'
      dependencies: [ branch_on_registry_stg_supplier_initialization ]
    dbt_run_registry_stg_supplier_full_refresh:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_supplier'
      full_refresh: True
      dependencies: [ branch_on_registry_stg_supplier_initialization ]
    dbt_run_dim_supplier:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'dim_supplier'
      trigger_rule: 'none_failed'
      dependencies: [ dbt_run_registry_stg_supplier, dbt_run_registry_stg_supplier_full_refresh ]