version: 2

sources:
  - name: raw
    database: raw
    schema: analytics_engineering_data_pipeline
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
  - name: elementary
    database: analytics
    schema: analytics_engineering_data_pipeline_elementary
    tables:
      - name: dbt_tests
      - name: elementary_test_results
  - name: metadata
    database: analytics
    schema: information_schema
    tables:
      - name: tables
      - name: views