setup_project:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-21
    retries: 1
    retry_delay_sec: 60
    snowflake_conn_id: snowflake
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To setup the dbt project"
  tasks:
    dbt_debug:
      operator: airflow.operators.bash.BashOperator
      bash_command: 'dbt debug'
    dbt_deps:
      operator: airflow_dbt.operators.dbt_operator.DbtDepsOperator
      dependencies: [ dbt_debug ]
    create_incremental_tables:
      operator: airflow.providers.snowflake.operators.snowflake.SnowflakeOperator
      sql: create_incremental_tables.sql
      dependencies: [ dbt_deps ]
    dbt_run_elementary:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      select: 'elementary'
      dependencies: [ create_incremental_tables ]