registry_dim_customer:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-20
    retries: 1
    retry_delay_sec: 60
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized customers' dimension table"
  tasks:
    dbt_snapshot_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_customer'
    trigger_nation_dag:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'int_nation_2'
      wait_for_completion: True
      deferrable: True
    dbt_run_registry_stg_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_customer'
      dependencies: [ dbt_snapshot_customer ]
    dbt_test_registry_stg_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'registry_stg_customer'
      dependencies: [ dbt_run_registry_stg_customer ]
    dbt_run_registry_dim_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_dim_customer'
      dependencies: [ trigger_nation_dag, dbt_test_registry_stg_customer ]
    dbt_test_registry_dim_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'registry_dim_customer'
      dependencies: [ dbt_run_registry_dim_customer ]