registry_dim_customer:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-20
    retries: 1
    retry_delay_sec: 60
    snowflake_conn_id: snowflake
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize historicized customers' dimension table"
  tasks:
    dbt_snapshot_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_customer'
    check_int_nation_existence:
      operator: airflow.providers.snowflake.operators.snowflake.SnowflakeCheckOperator
      sql: check_int_nation_existence.sql
    trigger_nation_dag:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'int_nation'
      wait_for_completion: True
      deferrable: True
      failed_states: ['failed']
      trigger_rule: ['all_success']
      dependencies: [ check_int_nation_existence ]
    dbt_run_registry_stg_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_stg_customer'
      dependencies: [ dbt_snapshot_customer ]
    dbt_test_registry_stg_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'registry_stg_customer'
      dependencies: [ dbt_run_registry_stg_customer ]
    dbt_run_registry_dim_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'registry_dim_customer'
      dependencies: [ trigger_nation_dag, dbt_test_registry_stg_customer ]
    dbt_test_registry_dim_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'registry_dim_customer'
      dependencies: [ dbt_run_registry_dim_customer ]
int_nation:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-08
    retries: 1
    retry_delay_sec: 60
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize nations' intermediate table"
  tasks:
    dbt_run_stg_nation:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'stg_nation'
    dbt_test_stg_nation:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'stg_nation'
      dependencies: [ dbt_run_stg_nation ]
    dbt_run_stg_region:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'stg_region'
    dbt_test_stg_region:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'stg_region'
      dependencies: [ dbt_run_stg_region ]
    dbt_run_int_nation:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'int_nation'
      dependencies: [ dbt_test_stg_nation, dbt_test_stg_region ]
    dbt_test_int_nation:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'int_nation'
      dependencies: [ dbt_run_int_nation ]