CREATE STORAGE INTEGRATION gcs_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'GCS'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('gcs://data-ingestion-tpch/')

DESC STORAGE INTEGRATION gcs_int

--DROP STORAGE INTEGRATION gcs_int