dim_customer_2:
  default_args:
    owner: 'v.folin@reply.it'
    start_date: 2023-12-08
    retries: 1
    retry_delay_sec: 60
  schedule_interval: None
  dagrun_timeout_sec: 3600
  description: "To materialize customers' dimension table"
  tasks:
    dbt_snapshot_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtSnapshotOperator
      models: 'snapshot_customer'
    check_customer_freshness:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      select: 'stg_customer, tag:freshness'
      dependencies: [ dbt_snapshot_customer ]
    branch_on_customer_freshness:
      operator: airflow.operators.python.BranchPythonOperator
      python_callable_name: branch_func_on_customer_freshness
      python_callable_file: /home/airflow/gcs/dags/dag_factory_version/current/individuals_factory/utils.py
      provide_context: True
      dependencies: [ check_customer_freshness ]
    trigger_nation_dag:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: 'int_nation_2'
      wait_for_completion: True
      trigger_rule: 'all_done'
      dependencies: [ branch_on_customer_freshness, dbt_test_stg_customer ]
    dbt_run_stg_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'stg_customer'
      dependencies: [ branch_on_customer_freshness ]
    dbt_test_stg_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'stg_customer'
      dependencies: [ dbt_run_stg_customer ]
    dbt_run_dim_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtRunOperator
      models: 'dim_customer'
      dependencies: [ trigger_nation_dag ]
    dbt_test_dim_customer:
      operator: airflow_dbt.operators.dbt_operator.DbtTestOperator
      models: 'dim_customer'
      dependencies: [ dbt_run_dim_customer ]