name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  gcp:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'synchronize-dags'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'dags'
        destination: 'europe-west4-demo-dbt-snowf-15fd2dcb-bucket/'
        gzip: false

    - id: 'synchronize-dbt-project'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '../'
        destination: 'europe-west4-demo-dbt-snowf-15fd2dcb-bucket/data/dbt'
        process_gcloudignore: true
        gzip: false
