# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   syncronize:

      runs-on: ubuntu-latest
      
      permissions:
        contents: 'read'
        id-token: 'write'

      steps:
      - id: 'checkout'
        uses: 'actions/checkout@v3'
  
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
  
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'snapshots/orders_snapshot.sql'
          destination: 'europe-west4-demo-dbt-snowf-15fd2dcb-bucket/data/dbt/snapshots'
              
